<?php
/**
 * @file
 */

include_once('humanitarianresponse_i18n.features.inc');

/**
 * Implements hook_i18n_object_info_alter(&$info)
 */
function humanitarianresponse_i18n_i18n_object_info_alter(&$info) {
  $info['taxonomy_term']['key'] = 'uuid';
  $info['taxonomy_vocabulary']['key'] = 'machine_name';
  $info['menu_link']['key'] = 'uuid';
}

/**
 * Implements hook_uuid_sync()
 */
function humanitarianresponse_i18n_uuid_sync() {
  module_load_include('inc', 'uuid', 'uuid.features.menu');
  $items = db_select('menu_links', 'm')
      ->fields('m')
      ->execute()
      ->fetchAllAssoc('mlid', PDO::FETCH_ASSOC);
  foreach ($items as $item) {
    if (empty($item['uuid'])) {
      $copy = $item;
      uuid_menu_link_make_universal($copy);
      $uuid = $copy['uuid_menu_name'].':'.$copy['uuid_link_path'];
      $item['uuid'] = $uuid;
      db_update('menu_links')
        ->fields(array(
          'uuid' => $uuid
        ))
        ->condition('mlid', $item['mlid'])
        ->execute();
    }
  }
}

/**
 * Implements hook_menu_link_insert()
 */
function humanitarianresponse_i18n_menu_link_insert($link) {
  module_load_include('inc', 'uuid', 'uuid.features.menu');
  uuid_menu_link_make_universal($link);
  $uuid = $link['uuid_menu_name'].':'.$link['uuid_link_path'];
  db_update('menu_links')
    ->fields(array(
      'uuid' => $uuid,
    ))
    ->condition('mlid', $link['mlid'])
    ->execute();
}
    
