<?php
/**
 * @file
 */

/**
 * Implements hook_enable()
 */
/*function humanitarianresponse_i18n_enable() {
  // Make main menu translatable
  $menu = menu_load('main-menu');
  $menu['i18n_mode'] = I18N_MODE_MULTIPLE;
  i18n_menu_menu_update($menu);
  
  // Enable URL in language negotation
  include_once DRUPAL_ROOT . '/includes/language.inc';
  include_once DRUPAL_ROOT . '/includes/locale.inc';
  $info = language_negotiation_info();
  $negotiation = array(
    LOCALE_LANGUAGE_NEGOTIATION_URL => $info[LOCALE_LANGUAGE_NEGOTIATION_URL],
    LANGUAGE_NEGOTIATION_DEFAULT => $info[LANGUAGE_NEGOTIATION_DEFAULT]
  );
  language_negotiation_set('language', $negotiation);
  foreach ($info as $id => $provider) {
    $providers_weight[$id] = language_provider_weight($provider);
  }
  variable_set('locale_language_providers_weight_language', $providers_weight);
  language_types_set();
}*/

/**
 * Implements hook_i18n_object_info_alter(&$info)
 */
function humanitarianresponse_i18n_i18n_object_info_alter(&$info) {
  $info['taxonomy_term']['key'] = 'uuid';
  $info['taxonomy_vocabulary']['key'] = 'machine_name';
  /*$info['menu_link']['key'] = array('menu_name', 'link_path');*/
}

/**
 * Implements hook_uuid_sync()
 */
function humanitarianresponse_i18n_uuid_sync() {
  module_load_include('inc', 'uuid', 'uuid.features.menu');
  $items = db_select('menu_links', 'm')
      ->fields('m')
      ->execute()
      ->fetchAllAssoc('mlid', PDO::FETCH_ASSOC);
  foreach ($items as $item) {
    if (empty($item['uuid'])) {
      $copy = $item;
      uuid_menu_link_make_universal($copy);
      $uuid = $copy['uuid_menu_name'].':'.$copy['uuid_link_path'];
      $item['uuid'] = $uuid;
      db_update('menu_links')
        ->fields(array(
          'uuid' => $uuid
        ))
        ->condition('mlid', $item['mlid'])
        ->execute();
    }
  }
}
